### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by victormaoya** [Boaz-Maroko/Comic_Book_Reader#1]
No module named 'rarfile'

**Comment by Boaz-Maroko** [comment]
Can you give more details?

**Comment by Boaz-Maroko** [comment]
Did you install all the dependencies?

**Comment by victormaoya** [comment]
Also, could you clarify on where this comic book is supposed to be in the
file structure.

**Comment by Boaz-Maroko** [comment]
Running the main.py file will open the comic book reader

**Comment by victormaoya** [comment]
I already ran that command.

**Comment by Boaz-Maroko** [comment]
Rerun the command. There was a bug with the requirement.txt file

**Comment by victormaoya** [comment]
[image: image.png]
